import './epipe-fix'; // Must be first — wraps stdout/stderr before any module writes

import {
  app,
  autoUpdater,
  BrowserWindow,
  dialog,
  globalShortcut,
  ipcMain,
  screen,
} from 'electron';
import settings from 'electron-settings';
import { existsSync, readdirSync } from 'fs';
import { DBPathMigrationManager } from './DBPathMigrationManager';
import { isMAS, ShortcutSettings, TrayGenerator } from './TrayGenerator';
import { bootstrap } from './server/server';
import { AIAssistantUIMode, isDebug } from './utility';
import {
  readClaudeSessions,
  searchClaudeSessions,
  detectActiveSessions,
  detectTerminalApp,
  openSession,
  copyResumeCommand,
  invalidateSessionCache,
  loadSessionEnrichment,
  loadLastAssistantResponses,
} from './claude-session-utility';
import {
  installHooks,
  removeHooks,
  isHooksInstalled,
  readAllStatuses,
  watchStatusDir,
  scanInitialStatuses,
  writeStatusFile,
  cleanupStaleStatuses,
  SessionStatus,
} from './session-status-hooks';
import {
  deleteRecentProjectRecord,
  openVSCodeBasedIDE,
  readVSCodeBasedIDEState,
  updateIDEDataPath,
} from './vscode-based-ide-utility';

import * as os from 'os';
import * as path from 'path';

const clipboard = require('electron').clipboard;

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const SWITCHER_WINDOW_WEBPACK_ENTRY: string;
declare const SWITCHER_WINDOW_PRELOAD_WEBPACK_ENTRY: string;
// AI Assistant window entry point
declare const AI_ASSISTANT_WINDOW_WEBPACK_ENTRY: string;
// Settings window entry point
declare const SETTINGS_WINDOW_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  // eslint-disable-line global-require
  app.quit();
}

let tray: TrayGenerator = null;
let switcherWindow: BrowserWindow = null;
let lastUpdateStatus: Record<string, string> | null = null;
let aiAssistantWindow: BrowserWindow = null; // Track the AI Assistant window
let settingsWindow: BrowserWindow = null; // Track the settings window
let serverProcess: any;

const WIN_WIDTH = 800;
const WIN_HEIGHT = 600;

const getWindowPosition = () => {
  const primaryDisplay = screen.getPrimaryDisplay();
  const { width, height } = primaryDisplay.workAreaSize;

  const x = Math.round(width / 2 - WIN_WIDTH / 2);
  const y = Math.round(height / 2 - WIN_HEIGHT / 2);

  return { x, y };
};

// ref: https://blog.logrocket.com/building-a-menu-bar-application-with-electron-and-react/
// NOTE: setVisibleOnAllWorkspaces is needed ?
const showSwitcherWindow = () => {
  let window = getSwitcherWindow();
  
  if (!window) {
    // Recreate window if it has been destroyed
    switcherWindow = createSwitcherWindow();
    window = switcherWindow;
  }
  
  const position = getWindowPosition();
  window.setPosition(position.x, position.y, false);
  window.show();
  // mainWindow.setVisibleOnAllWorkspaces(true);
  window.focus();
  // mainWindow.setVisibleOnAllWorkspaces(false);
};

const showAIAssistantWindow = () => {
  const position = getWindowPosition();
  aiAssistantWindow.setPosition(position.x, position.y, false);
  aiAssistantWindow.show();
  // mainWindow.setVisibleOnAllWorkspaces(true);
  aiAssistantWindow.focus();
  // mainWindow.setVisibleOnAllWorkspaces(false);
};

// Handle chat messages from the AI Assistant window
ipcMain.on(
  'send-chat-message',
  (event, message, messageHistory, additionalContext) => {
    // Get the window that sent this message
    const sender = BrowserWindow.fromWebContents(event.sender);
    if (sender && !sender.isDestroyed()) {
      // Forward the message to AnthropicService with additional context
      anthropicService.handleChatMessage(
        message,
        sender,
        messageHistory,
        additionalContext,
      );
    }
  },
);

// Handle UI mode changes to track the current mode
ipcMain.on('ui-mode-changed', (event, mode) => {
  lastUIMode = mode;
});

// Handle insight completion status
ipcMain.on('insight-completed', (event, completed) => {
  lastInsightCompleted = completed; // Keep the same variable name for backward compatibility
});

// Legacy event for backward compatibility
ipcMain.on('ai-assistant-insight-completed', (event, completed) => {
  lastInsightCompleted = completed;
});

// Conversation history IPC handlers
ipcMain.handle('save-conversation', async (_, conversation) => {
  try {
    const response = await axios.post(`${API_URL}/conversations`, conversation);
    return response.data;
  } catch (error) {
    console.error('Error saving conversation:', error);
    throw error;
  }
});

ipcMain.handle('update-conversation', async (_, id, conversation) => {
  try {
    const response = await axios.put(
      `${API_URL}/conversations/${id}`,
      conversation,
    );
    return response.data;
  } catch (error) {
    console.error('Error updating conversation:', error);
    throw error;
  }
});

ipcMain.handle('get-conversation', async (_, id) => {
  try {
    const response = await axios.get(`${API_URL}/conversations/${id}`);
    return response.data;
  } catch (error) {
    console.error('Error fetching conversation:', error);
    throw error;
  }
});

ipcMain.handle('get-conversations', async (_, params = {}) => {
  try {
    const response = await axios.get(`${API_URL}/conversations`, { params });
    return response.data;
  } catch (error) {
    console.error('Error fetching conversations:', error);
    throw error;
  }
});

ipcMain.handle('get-latest-conversation', async (_, isFromCode) => {
  try {
    const params = isFromCode !== undefined ? { isFromCode } : {};
    const response = await axios.get(`${API_URL}/conversations/latest`, {
      params,
    });
    return response.data;
  } catch (error) {
    console.error('Error fetching latest conversation:', error);
    throw error;
  }
});

ipcMain.handle('delete-conversation', async (_, id) => {
  try {
    const response = await axios.delete(`${API_URL}/conversations/${id}`);
    return response.data;
  } catch (error) {
    console.error('Error deleting conversation:', error);
    throw error;
  }
});

ipcMain.handle('add-message-to-conversation', async (_, id, message) => {
  try {
    const response = await axios.post(
      `${API_URL}/conversations/${id}/messages`,
      message,
    );
    return response.data;
  } catch (error) {
    console.error('Error adding message to conversation:', error);
    throw error;
  }
});

ipcMain.handle('search-conversations', async (_, searchTerm) => {
  try {
    const response = await axios.get(`${API_URL}/conversations/search`, {
      params: { term: searchTerm },
    });
    return response.data;
  } catch (error) {
    console.error('Error searching conversations:', error);
    throw error;
  }
});

// Check if switcherWindow exists and is not destroyed
const getSwitcherWindow = () => {
  return switcherWindow && !switcherWindow.isDestroyed() ? switcherWindow : null;
};

// Hide the switcher window if it exists and is not destroyed
const hideSwitcherWindow = () => {
  const window = getSwitcherWindow();
  if (window) {
    window.hide();
  }
};

const onBlur = (event: any) => {
  hideSwitcherWindow();
};

const onFocus = (event: any) => {
  // Don't invalidate session cache on every focus - cache has 5s TTL
  const window = getSwitcherWindow();
  if (window) {
    window.webContents.send('window-focus');
  }
};

const createAIAssistantWindow = (): BrowserWindow => {
  // If window already exists, just return it - visibility is handled by the caller
  if (aiAssistantWindow && !aiAssistantWindow.isDestroyed()) {
    if (aiAssistantWindow.isMinimized()) {
      aiAssistantWindow.restore();
    }
    aiAssistantWindow.focus();
    return aiAssistantWindow;
  }

  // Calculate position to create a semi-transparent floating window
  const primaryDisplay = screen.getPrimaryDisplay();
  const { width, height } = primaryDisplay.workAreaSize;

  // Create window with 800x600 size positioned at the center of the screen
  // Performance optimizations added
  aiAssistantWindow = new BrowserWindow({
    width: 800,
    height: 600,
    x: Math.round(width / 2 - 400),
    y: Math.round(height / 2 - 300),
    webPreferences: {
      preload: SWITCHER_WINDOW_PRELOAD_WEBPACK_ENTRY,
      devTools: false, // Always enable DevTools for debugging
      nodeIntegration: false,
      contextIsolation: true,
      // Performance optimizations
      backgroundThrottling: false, // Prevents throttling when window is in background
      spellcheck: false, // Disable spellcheck for better performance
      enableBlinkFeatures: 'CompositorThreadedScrollbarScrolling', // Use threaded scrolling
    },
    show: true, // Show immediately for better perceived performance
    frame: true,
    fullscreenable: false,
    resizable: true,
    // Solid background
    backgroundColor: '#2d2d2d', // Pre-paint with background color
    opacity: 1.0,
    // Always on top to ensure visibility
    alwaysOnTop: true,
    // Performance optimization
    paintWhenInitiallyHidden: true, // Paint even when initially hidden
  });

  // Load the AI Assistant renderer
  aiAssistantWindow.loadURL(AI_ASSISTANT_WINDOW_WEBPACK_ENTRY);

  // Open DevTools in detached mode to help debug
  if (isDebug) {
    aiAssistantWindow.webContents.openDevTools({ mode: 'detach' });
  }

  // Handle window closed event
  aiAssistantWindow.on('closed', () => {
    aiAssistantWindow = null;
  });

  /** TODO: add window.on('move', () => { */

  return aiAssistantWindow;
};

// Legacy function for backward compatibility - will be removed after migration
const createCodeAIAssistantWindow = (): BrowserWindow => {
  return createAIAssistantWindow();
};

const createSettingsWindow = (
  settingsType: string = 'ai_assistant_setting',
): BrowserWindow => {
  // If window already exists, just return it - visibility is handled by the caller
  if (settingsWindow && !settingsWindow.isDestroyed()) {
    if (settingsWindow.isMinimized()) {
      settingsWindow.restore();
    }
    settingsWindow.focus();

    // Send message to switch to the specified settings type
    if (settingsType === 'ai_assistant_setting') {
      settingsWindow.webContents.send('open-ai-assistant-settings');
    } else if (settingsType === 'apiKey') {
      settingsWindow.webContents.send('open-api-key-settings');
    } else if (settingsType === 'leftClick') {
      settingsWindow.webContents.send('open-left-click-settings');
    } else if (settingsType === 'idePreference') {
      settingsWindow.webContents.send('open-ide-settings');
    }

    return settingsWindow;
  }

  // Calculate position for settings window
  const primaryDisplay = screen.getPrimaryDisplay();
  const { width, height } = primaryDisplay.workAreaSize;

  // Create settings window - increased height to ensure save message is visible
  settingsWindow = new BrowserWindow({
    width: 800,
    height: 650, // Increased from 600 to ensure save message is fully visible
    x: Math.round(width / 2 - 400),
    y: Math.round(height / 2 - 325), // Adjusted y position to center the taller window
    webPreferences: {
      preload: SWITCHER_WINDOW_PRELOAD_WEBPACK_ENTRY,
      devTools: false,
      nodeIntegration: false,
      contextIsolation: true,
    },
    show: true,
    frame: true,
    fullscreenable: false,
    resizable: true,
    backgroundColor: '#1a1a1a',
  });

  // Load the settings renderer with the appropriate settings type as a query parameter
  settingsWindow.loadURL(
    `${SETTINGS_WINDOW_WEBPACK_ENTRY}?type=${settingsType}`,
  );

  // Open DevTools in detached mode to help debug
  if (isDebug) {
    settingsWindow.webContents.openDevTools({ mode: 'detach' });
  }

  // Handle window closed event
  settingsWindow.on('closed', () => {
    settingsWindow = null;
  });

  return settingsWindow;
};

const createSwitcherWindow = (): BrowserWindow => {
  // Create the browser window.
  const window = new BrowserWindow({
    // maximizable: false,
    // minimizable: false, // ux not good
    height: 600,
    width: 800,
    webPreferences: {
      preload: SWITCHER_WINDOW_PRELOAD_WEBPACK_ENTRY,
      devTools: true, //isDebug,
    },

    // hide window by default
    show: false,
    frame: false,
    fullscreenable: false,
    resizable: false,
    backgroundColor: '#1e1e1e',
  });

  // and load the index.html of the app.
  window.loadURL(SWITCHER_WINDOW_WEBPACK_ENTRY);

  // Open external links in default browser
  const { shell } = require('electron');
  window.webContents.setWindowOpenHandler(({ url }: { url: string }) => {
    if (url.startsWith('https://') || url.startsWith('http://')) {
      shell.openExternal(url);
    }
    return { action: 'deny' as const };
  });

  // Disable Cmd+R reload (not useful for menu bar app)
  window.webContents.on('before-input-event', (_event: any, input: any) => {
    if (input.meta && input.key === 'r' && !input.control) {
      _event.preventDefault();
    }
  });

  // if (isDebug) {
  //   window.webContents.openDevTools({ mode: 'detach' });
  // }

  if (tray) {
    // TODO: change to use some Tray method & not set tray here
    tray.attachedWindow = window;
  }

  window.on('blur', onBlur);
  window.on('focus', onFocus);

  // mainWindow.on('close', function (event) {
  //   console.log("mainWindow close");
  //   // if below is setup, app.window-all-closed will not be fired
  //   // if(!application.isQuiting){
  //   // event.preventDefault();
  //   // mainWindow.hide();
  //   // // }
  //   // return false;
  // });

  window.on('move', () => {
    const bounds = switcherWindow.getBounds();
    const currentDisplay = screen.getDisplayNearestPoint({
      x: bounds.x,
      y: bounds.y,
    });

    showSwitcherWindow();
  });

  return window;
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  if (isDebug) {
    console.log('on ready');
  }
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (isDebug) {
    console.log('window-all-closed');
  }
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

/** not triggered yet */
app.on('activate', () => {
  if (isDebug) {
    console.log('activate');
  }
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    switcherWindow = createSwitcherWindow();
  }
});

/** https://www.electronjs.org/docs/latest/tutorial/ipc */
ipcMain.on('invoke-vscode', (event, path: string, option: string) => {
  // if (isDebug) {
  //   console.log('invoke', { /*event,*/ path });
  //   tray.tray.setTitle(`CodeV(${path ? path[path.length - 1] : 'n'})`);
  // }

  if (!existsSync(path)) {
    if (isDebug) {
      console.log('Path does not exist:', path);
    }
    // send message to Electron, not really use now, just in case
    const window = getSwitcherWindow();
    if (window) {
      window.webContents.send('xwin-not-found');
      
      dialog.showMessageBox(window, {
      message: `Path does not exist: ${path}`,
      buttons: ['OK'],
      defaultId: 0, // bound to buttons array
      cancelId: 1, // bound to buttons array
      });
    }

    return;
  }

  const ifForceReuseWin = option ? true : false;

  openVSCodeBasedIDE(path, ifForceReuseWin);

  hideSwitcherWindow();
});

ipcMain.on('pop-alert', (event, alert: string) => {
  const window = getSwitcherWindow();
  if (window) {
    dialog.showMessageBox(window, {
    message: alert,
    buttons: ['OK'],
    defaultId: 0, // bound to buttons array
    cancelId: 1, // bound to buttons array
    });
  }
});

ipcMain.on('search-working-folder', (event, path: string) => {
  if (!path) {
    return;
  }

  // console.time('readdir');

  // 0.2ms ~ 100 item
  // 0.27ms ~ 2item
  // 0.4ms for git folder, ~200
  /** TODO: use async way to improve performance */
  const directoriesInDIrectory = readdirSync(path, {
    withFileTypes: true,
  });

  /** readdir-all subfolder: 96.554ms */
  const returnPathlist = [];
  // const subListCount = 0; // 3785
  for (const item of directoriesInDIrectory) {
    if (item.name.startsWith('.')) {
      continue;
    }

    const itemPath = path + '/' + item.name;
    if (!item.isDirectory()) {
      if (item.name.endsWith('.code-workspace')) {
        returnPathlist.push(itemPath);
      }
      continue;
    }
    returnPathlist.push(itemPath);

    // TODO: this is macOs path style. use Node.js path.join()
    const targetSpacePath = itemPath + '/' + item.name + '.code-workspace';
    if (existsSync(targetSpacePath)) {
      returnPathlist.push(targetSpacePath);
      // if (targetSpacePath.endsWith('.code-workspace')) {
      //   console.log('targetSpacePath,', targetSpacePath);
      // }
    }
  }

  // console.timeEnd('readdir');
  // console.log({ returnPathlist: returnPathlist.length });

  const window = getSwitcherWindow();
  if (window) {
    window.webContents.send('working-folder-iterated', returnPathlist);
  }
});

ipcMain.on('hide-app', (event) => {
  hideSwitcherWindow();
});

ipcMain.on('open-external', (_event, url: string) => {
  const { shell } = require('electron');
  shell.openExternal(url);
});

ipcMain.on('close-app-click', async (event) => {
  // Hide windows before quit to prevent white flash from xterm container
  switcherWindow?.hide();
  aiAssistantWindow?.hide();
  app.quit();
});

// Settings window handlers
ipcMain.on('open-settings', (event, settingsType = 'ai_assistant_setting') => {
  createSettingsWindow(settingsType);
});

// Create Settings windows from tray menu
ipcMain.on('open-ai-assistant-settings', () => {
  createSettingsWindow('ai_assistant_setting');
});

ipcMain.on('open-api-key-settings', () => {
  createSettingsWindow('apiKey');
});

ipcMain.on('open-left-click-settings', () => {
  createSettingsWindow('leftClick');
});

ipcMain.on('open-ide-settings', () => {
  createSettingsWindow('idePreference');
});

// Import our Anthropic service
import axios from 'axios';
import anthropicService from './AnthropicService';

// API URL for the local NestJS server
const API_URL = 'http://localhost:55688';

// Import the function to update IDE mode and IDE enum
import { IDEMode } from './ide-enum';
import { detectActiveIDEProjects, updateCurrentIDEMode } from './vscode-based-ide-utility';

// Track user settings
let userSettings = {
  leftClickBehavior: 'switcher_window', // Default behavior
  preferredIDE: IDEMode.VSCode, // Default to VSCode
};

// Track the last analyzed code to detect changes
let lastAnalyzedCodeToGetInsight = '';
// Track the last used UI mode to restore it when reopening
let lastUIMode = AIAssistantUIMode.SMART_CHAT;
// Track whether an insight was completed for the current code
let lastInsightCompleted = false;

ipcMain.on('open-folder-selector', async (event) => {
  const result = await dialog.showOpenDialog({
    properties: ['openDirectory'],
    securityScopedBookmarks: true,
    // properties: ['openFile', 'multiSelections'],
  });
  /** https://gist.github.com/ngehlert/74d5a26990811eed59c635e49134d669 */
  const { canceled, filePaths, bookmarks } = result;
  if (canceled || filePaths.length === 0) {
    return;
  }
  if (bookmarks && bookmarks.length) {
    // store the bookmark key
    if (isMAS()) {
      await settings.set('security-scoped-bookmark', bookmarks[0]);
    }
  }

  const folderPath = filePaths[0];

  const window = getSwitcherWindow();
  if (window) {
    window.webContents.send('folder-selected', folderPath);
  }

  // Update terminal CWD if PTY is running (#88)
  if (ptyProcess) {
    const home = require('os').homedir();
    const rest = folderPath.startsWith(home) ? folderPath.slice(home.length) : null;
    // POSIX-safe: single-quote the path, escape embedded single quotes
    const escaped = (rest !== null ? rest : folderPath).replace(/'/g, "'\\''");
    const cdPath = rest !== null ? `~'${escaped}'` : `'${escaped}'`;
    ptyProcess.write(`cd ${cdPath} && clear\n`);
  }
});

ipcMain.on('ide-preference-changed', async (_event, preferredIDE: string) => {
  userSettings.preferredIDE = preferredIDE as IDEMode;
  updateCurrentIDEMode(preferredIDE);
  console.log('IDE preference updated to:', preferredIDE);
  try {
    await fetch('http://localhost:55688/ai-assistant-settings', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ preferredIDE }),
    });
  } catch (error) {
    if (isDebug) {
      console.error('Failed to save IDE preference:', error);
    }
  }
});

ipcMain.handle('get-ide-preference', () => {
  return userSettings.preferredIDE;
});

ipcMain.handle('get-is-mas', () => {
  return isMAS();
});

ipcMain.handle('get-left-click-behavior', () => {
  return userSettings.leftClickBehavior;
});

ipcMain.on('set-left-click-behavior', async (_event, behavior: string) => {
  userSettings.leftClickBehavior = behavior;
  try {
    await fetch('http://localhost:55688/ai-assistant-settings', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ leftClickBehavior: behavior }),
    });
  } catch (error) {
    if (isDebug) {
      console.error('Failed to save left-click behavior:', error);
    }
  }
});

ipcMain.handle('check-ide-data-access', async (_event, ideMode: string) => {
  const bookmarkKey = ideMode === 'Cursor'
    ? 'security-scoped-bookmark-ide-data-cursor'
    : 'security-scoped-bookmark-ide-data-vscode';
  const pathKey = ideMode === 'Cursor'
    ? 'ide-data-path-cursor'
    : 'ide-data-path-vscode';
  const bookmark = await settings.get(bookmarkKey);
  const storedPath = await settings.get(pathKey);
  return !!(bookmark || storedPath);
});

ipcMain.on('open-ide-data-selector', async (event, ideMode: string) => {
  const homePath = os.homedir();
  const idePath = ideMode === 'Cursor'
    ? path.join(homePath, 'Library/Application Support/Cursor/User/globalStorage')
    : path.join(homePath, 'Library/Application Support/Code/User/globalStorage');
  const bookmarkKey = ideMode === 'Cursor'
    ? 'security-scoped-bookmark-ide-data-cursor'
    : 'security-scoped-bookmark-ide-data-vscode';
  const pathKey = ideMode === 'Cursor'
    ? 'ide-data-path-cursor'
    : 'ide-data-path-vscode';
  const result = await dialog.showOpenDialog({
    properties: ['openDirectory'],
    securityScopedBookmarks: true,
    defaultPath: idePath,
    message: 'Select the globalStorage folder to grant access to IDE recent projects data',
  });
  const { canceled, filePaths, bookmarks } = result;
  if (canceled || filePaths.length === 0) {
    return;
  }
  console.log('IDE data selector result:', { filePaths, hasBookmarks: !!bookmarks?.length, ideMode });
  // Store the bookmark and the actual selected path
  await settings.set(bookmarkKey, bookmarks?.[0] || 'granted');
  await settings.set(pathKey, filePaths[0]);
  // Update the override path for reading SQLite
  updateIDEDataPath(ideMode, filePaths[0]);
  if (isMAS() && bookmarks && bookmarks.length) {
    app.startAccessingSecurityScopedResource(bookmarks[0]);
  }
  // Notify the settings window that access was granted
  event.sender.send('ide-data-folder-selected', filePaths[0]);
});

ipcMain.on('fetch-vscode-based-sqlite', async (event) => {
  const resp = readVSCodeBasedIDEState();
  // console.log('readVSCodeBasedIDEState done: sent it to ui: ', resp);
  const window = getSwitcherWindow();
  if (window) {
    window.webContents.send('vscode-based-sqlite-read', resp);
  }
});
ipcMain.on('delete-vscode-based-sqlite-record', async (event, path: string) => {
  deleteRecentProjectRecord(path);
  const window = getSwitcherWindow();
  if (window) {
    window.webContents.send('vscode-based-sqlite-record-deleted');
  }
});

// Load settings from database with retry mechanism
const loadUserSettings = async () => {
  // Number of retries and delay between retries
  const maxRetries = 3;
  const retryDelay = 1000; // ms

  for (let attempt = 0; attempt < maxRetries; attempt++) {
    try {
      // Add timeout to the fetch request to avoid long waits
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 3000);

      const response = await fetch(
        'http://localhost:55688/ai-assistant-settings',
        {
          signal: controller.signal,
        },
      );

      clearTimeout(timeoutId);

      if (response.ok) {
        const settings = await response.json();
        if (settings) {
          userSettings.leftClickBehavior =
            settings.leftClickBehavior || 'switcher_window';
          userSettings.preferredIDE = settings.preferredIDE || IDEMode.VSCode;

          // Apply the IDE mode setting
          updateCurrentIDEMode(userSettings.preferredIDE);
        }
        return; // Success, exit the function
      }
    } catch (error) {
      // Only log on final attempt
      if (attempt === maxRetries - 1) {
        if (isDebug) {
          console.error('Failed to load user settings after retries:', error);
        }
      } else {
        // Wait before next retry
        await new Promise((resolve) => setTimeout(resolve, retryDelay));
      }
    }
  }

  // If we reached here, all attempts failed
  if (isDebug) {
    console.log('Using default settings after failed load attempts');
  }
};

// Handle Tray icon left-click based on user settings
const trayToggleEvtHandler = async () => {
  if (isDebug) {
    console.log('tray toggle callback');
  }

  // Make sure settings are loaded
  await loadUserSettings();

  // Handle different click behaviors
  if (userSettings.leftClickBehavior === 'ai_assistant') {
    // Open AI Assistant with clipboard content
    const selectedCode = clipboard.readText().trim();

    if (selectedCode && selectedCode.length > 0) {
      // Create or focus AI Assistant window
      const aiAssistantWin = createAIAssistantWindow();

      // Make sure the window is visible
      showAIAssistantWindow();

      // Handle loading state properly
      const processCode = () => {
        // Set UI mode to INSIGHT_CHAT
        aiAssistantWin.webContents.send(
          'set-ui-mode',
          AIAssistantUIMode.INSIGHT_CHAT,
          {
            code: selectedCode,
          },
        );

        // Send the code and start analysis
        aiAssistantWin.webContents.send(
          'code-to-generate-insight',
          selectedCode,
        );
        anthropicService.analyzeCodeToGetInsight(selectedCode, aiAssistantWin);
      };

      // If window is still loading, wait for it to load
      if (aiAssistantWin.webContents.isLoadingMainFrame()) {
        aiAssistantWin.webContents.once('did-finish-load', processCode);
      } else {
        // Window already loaded, process immediately
        processCode();
      }
    } else {
      // No code in clipboard, open Smart Chat instead (better UX than opening main window)
      // Create or focus AI Assistant window
      const aiAssistantWin = createAIAssistantWindow();

      // Show window first for better perceived performance
      showAIAssistantWindow();

      // Set UI mode to SMART_CHAT
      if (aiAssistantWin.webContents.isLoadingMainFrame()) {
        aiAssistantWin.webContents.once('did-finish-load', () => {
          aiAssistantWin.webContents.send(
            'set-ui-mode',
            AIAssistantUIMode.SMART_CHAT,
          );
        });
      } else {
        aiAssistantWin.webContents.send(
          'set-ui-mode',
          AIAssistantUIMode.SMART_CHAT,
        );
      }
    }
  } else if (userSettings.leftClickBehavior === 'pure_chat') {
    // Open Smart Chat interface

    // Check if AI Assistant window already exists
    if (aiAssistantWindow && !aiAssistantWindow.isDestroyed()) {
      // If window is visible, toggle visibility (hide it)
      if (aiAssistantWindow.isVisible()) {
        aiAssistantWindow.hide();
        return;
      }

      // Show the existing window
      aiAssistantWindow.show();

      // Set UI mode to SMART_CHAT
      if (aiAssistantWindow.webContents.isLoadingMainFrame()) {
        aiAssistantWindow.webContents.once('did-finish-load', () => {
          aiAssistantWindow.webContents.send(
            'set-ui-mode',
            AIAssistantUIMode.SMART_CHAT,
          );
        });
      } else {
        aiAssistantWindow.webContents.send(
          'set-ui-mode',
          AIAssistantUIMode.SMART_CHAT,
        );
      }
    } else {
      // Create a new window
      aiAssistantWindow = createAIAssistantWindow();

      // Set UI mode to SMART_CHAT
      if (aiAssistantWindow.webContents.isLoadingMainFrame()) {
        aiAssistantWindow.webContents.once('did-finish-load', () => {
          aiAssistantWindow.webContents.send(
            'set-ui-mode',
            AIAssistantUIMode.SMART_CHAT,
          );
        });
      } else {
        aiAssistantWindow.webContents.send(
          'set-ui-mode',
          AIAssistantUIMode.SMART_CHAT,
        );
      }
    }
  } else {
    // Default behavior - toggle main window
    if (BrowserWindow.getAllWindows().length === 0) {
      if (isDebug) {
        console.log('no window, create one');
      }
      switcherWindow = createSwitcherWindow();
      showSwitcherWindow();
    } else {
      const window = getSwitcherWindow();
      
      if (window && window.isVisible()) {
        if (isDebug) {
          console.log('is visible, to hide');
        }
        hideSwitcherWindow();
      } else if (window) {
        if (isDebug) {
          console.log('is not visible, to show');
        }
        showSwitcherWindow();
      } else {
        if (isDebug) {
          console.log('window was destroyed, creating new one');
        }
        switcherWindow = createSwitcherWindow();
        showSwitcherWindow();
      }
    }
  }
};

/**
 * what is the difference between whenReady & .on('ready)???
 */
(async () => {
  await app.whenReady();

  // Auto-update: check for updates via update.electronjs.org (non-MAS only)
  if (!isMAS()) {
    try {
      const { updateElectronApp, UpdateSourceType } = require('update-electron-app');
      updateElectronApp({
        updateSource: {
          type: UpdateSourceType.ElectronPublicUpdateService,
          repo: 'grimmerk/codev',
        },
        updateInterval: '1 hour',
        notifyUser: false,
      });

      const sendUpdateStatus = (data: Record<string, string>) => {
        lastUpdateStatus = data;
        switcherWindow?.webContents.send('update-status', data);
      };

      // Forward autoUpdater events to renderer for custom UI
      autoUpdater.on('checking-for-update', () => {
        sendUpdateStatus({ status: 'checking' });
      });
      autoUpdater.on('update-available', () => {
        sendUpdateStatus({ status: 'downloading' });
      });
      autoUpdater.on('update-not-available', () => {
        sendUpdateStatus({ status: 'up-to-date' });
      });
      autoUpdater.on('update-downloaded', (_event: any, releaseNotes: string, releaseName: string) => {
        sendUpdateStatus({ status: 'ready', releaseName });
      });
      autoUpdater.on('error', (err: Error) => {
        if (isDebug) {
          console.error('Auto-update error:', err);
        }
        sendUpdateStatus({ status: 'error', error: err.message });
      });
    } catch (e) {
      if (isDebug) {
        console.error('Auto-update init failed:', e);
      }
    }
  }

  switcherWindow = createSwitcherWindow();
  if (isDebug) {
    console.log('when ready');
  }

  // Pre-initialize aiAssistantWindow for faster first open
  // This is done after mainWindow is created, but before showing it
  // so that initial startup isn't slowed down
  setTimeout(() => {
    // Create AI Assistant window but keep it hidden
    aiAssistantWindow = createCodeAIAssistantWindow();
    aiAssistantWindow.hide(); // Ensure it's hidden

    // Preload PURE_CHAT mode for faster response
    if (aiAssistantWindow.webContents.isLoadingMainFrame()) {
      aiAssistantWindow.webContents.once('did-finish-load', () => {
        aiAssistantWindow.webContents.send(
          'set-ui-mode',
          AIAssistantUIMode.SMART_CHAT,
        );
      });
    } else {
      aiAssistantWindow.webContents.send(
        'set-ui-mode',
        AIAssistantUIMode.SMART_CHAT,
      );
    }
  }, 1000); // Delay by 1 second to not interfere with main window initialization

  // Initialize session status hooks (install if enabled, start watching)
  initSessionStatusHooks();

  // Pre-spawn terminal for faster first Terminal tab switch
  setTimeout(() => {
    if (!ptyProcess) {
      spawnTerminal();
    }
  }, 2000);

  // Add window closed event handler to AI Assistant window to recreate it when closed
  // This ensures the next opening will still be fast
  const setupaiAssistantWindowRebuild = () => {
    if (aiAssistantWindow && !aiAssistantWindow.isDestroyed()) {
      // Remove any previous listeners to avoid duplicates
      aiAssistantWindow.removeAllListeners('closed');

      // Add new closed listener
      aiAssistantWindow.on('closed', () => {
        // Store state before closing to decide what to do on reopen
        const previousAnalyzedCode = lastAnalyzedCodeToGetInsight;
        const previousUIMode = lastUIMode;

        // IMPORTANT: Don't reset tracking variables when window is closed
        // This allows us to remember the state when reopening with the same code content
        // We comment out these lines to preserve state across window close/open
        // lastAnalyzedCodeToGetInsight = '';
        // lastInsightCompleted = false;

        // Schedule recreation after a short delay
        setTimeout(() => {
          if (!aiAssistantWindow || aiAssistantWindow.isDestroyed()) {
            aiAssistantWindow = createCodeAIAssistantWindow();
            aiAssistantWindow.hide();
            setupaiAssistantWindowRebuild(); // Setup the listener again for the new window

            // Set PURE_CHAT mode as default for the recreated window
            if (aiAssistantWindow.webContents.isLoadingMainFrame()) {
              aiAssistantWindow.webContents.once('did-finish-load', () => {
                aiAssistantWindow.webContents.send(
                  'set-ui-mode',
                  AIAssistantUIMode.SMART_CHAT,
                );

                // Log window recreation for debugging
                if (isDebug) {
                  console.log(
                    'AI Assistant window recreated after close. Reset to SMART_CHAT mode.',
                  );
                  console.log(
                    `Previous mode: ${previousUIMode}, Previous code hash: ${previousAnalyzedCode.length > 0 ? 'has content' : 'empty'}`,
                  );
                }
              });
            } else {
              aiAssistantWindow.webContents.send(
                'set-ui-mode',
                AIAssistantUIMode.SMART_CHAT,
              );

              // Log window recreation for debugging
              if (isDebug) {
                console.log(
                  'AI Assistant window recreated after close. Reset to SMART_CHAT mode.',
                );
                console.log(
                  `Previous mode: ${previousUIMode}, Previous code hash: ${previousAnalyzedCode.length > 0 ? 'has content' : 'empty'}`,
                );
              }
            }
          }
        }, 500);
      });
    }
  };

  // Call this after the initial window is created
  setTimeout(setupaiAssistantWindowRebuild, 2000);

  DBPathMigrationManager.initPath();
  // console.log({
  //   node: process?.env?.NODE_ENV,
  //   DEBUG_PROD: process.env.DEBUG_PROD,
  //   isUnPackaged: isUnPackaged,
  // });
  const needVer = await DBPathMigrationManager.checkNeedMigration();
  if (needVer) {
    await DBPathMigrationManager.doMigrationToVersion(needVer);
  }
  if (isDebug) {
    console.log(
      'check db done. USE DBPATH:',
      DBPathMigrationManager.databaseFilePath,
    );
  }

  if (isMAS()) {
    const securityBookmark = (await settings.get(
      'security-scoped-bookmark',
    )) as string;
    if (securityBookmark) {
      app.startAccessingSecurityScopedResource(securityBookmark);
    }
    const ideConfigs = [
      { bookmarkKey: 'security-scoped-bookmark-ide-data-vscode', pathKey: 'ide-data-path-vscode', ideMode: 'VSCode' },
      { bookmarkKey: 'security-scoped-bookmark-ide-data-cursor', pathKey: 'ide-data-path-cursor', ideMode: 'Cursor' },
    ];
    for (const { bookmarkKey, pathKey, ideMode } of ideConfigs) {
      const ideBookmark = (await settings.get(bookmarkKey)) as string;
      const idePath = (await settings.get(pathKey)) as string;
      console.log(`IDE [${ideMode}] bookmark:`, ideBookmark ? 'found' : 'not found', 'path:', idePath || 'not set');
      if (ideBookmark && ideBookmark !== 'granted') {
        app.startAccessingSecurityScopedResource(ideBookmark);
      }
      if (idePath) {
        updateIDEDataPath(ideMode, idePath);
      }
    }
  }
  process.env.DATABASE_URL = `file:${DBPathMigrationManager.databaseFilePath}`;
  process.env.PRISMA_QUERY_ENGINE_LIBRARY = DBPathMigrationManager.queryExePath;
  await bootstrap();

  // Load user settings
  await loadUserSettings();

  let title = '';
  if (!isDebug) {
    title = ``;
  } else {
    // title = `CodeV(cmd+ctrl+r/e)`;
    title = `CodeV`;
    if (DBPathMigrationManager.needUpdate) {
      title = `${title}${'u.'}`;
    }
  }

  tray = new TrayGenerator(switcherWindow, title, trayToggleEvtHandler);

  // https://www.electronjs.org/docs/latest/tutorial/keyboard-shortcuts#global-shortcuts

  // Default shortcut accelerators
  const DEFAULT_SHORTCUTS: Record<string, string> = {
    quickSwitcher: 'Command+Control+R',
    aiInsight: 'Command+Control+E',
    aiChat: 'Command+Control+C',
    terminal: 'Command+Control+T',
  };

  // Shortcut callback: Quick Switcher
  const quickSwitcherCallback = () => {
    if (isDebug) {
      console.log('Command+Control+R triggered - always shows Switcher window');
    }

    if (BrowserWindow.getAllWindows().length === 0) {
      if (isDebug) {
        console.log('No window, creating main window');
      }
      switcherWindow = createSwitcherWindow();
      showSwitcherWindow();
    } else {
      const window = getSwitcherWindow();
      
      if (window && window.isVisible()) {
        if (isDebug) {
          console.log('Switcher window visible, hiding it');
        }
        hideSwitcherWindow();
      } else if (window) {
        if (isDebug) {
          console.log('Switcher window exists but hidden, showing it');
        }
        showSwitcherWindow();
      } else {
        if (isDebug) {
          console.log('Switcher window was destroyed, creating a new one');
        }
        switcherWindow = createSwitcherWindow();
        showSwitcherWindow();
      }
    }
  };

  // Shortcut callback: Smart Chat (Ctrl+Cmd+C)
  const aiChatCallback = () => {
    // Check if AI Assistant window already exists
    if (aiAssistantWindow && !aiAssistantWindow.isDestroyed()) {
      // If window is visible, check its current mode
      if (aiAssistantWindow.isVisible()) {
        // For now, just hide the window if it's visible (simplified toggle behavior)
        aiAssistantWindow.hide();
        return;
      } else {
        // Performance optimization: Show window immediately before setting mode
        // This improves perceived performance as the window appears faster
        aiAssistantWindow.show();

        // Use setTimeout with 0ms to ensure show() completes first
        setTimeout(() => {
          // We need to first load the latest conversation and THEN set UI mode
          // This ensures we have the conversation data before switching modes
          // Otherwise, setting mode will reinitialize messages and lose conversation data

          // First load the conversation
          console.log(
            'Sending load-latest-conversation event to restore previous chat',
          );
          aiAssistantWindow.webContents.send('load-latest-conversation');

          // Add a small delay before setting UI mode to ensure conversation loads first
          setTimeout(() => {
            console.log('Setting UI mode to SMART_CHAT');
            aiAssistantWindow.webContents.send(
              'set-ui-mode',
              AIAssistantUIMode.SMART_CHAT,
              { keepExistingMessages: true }, // Add flag to keep existing messages
            );
          }, 100); // Small delay to ensure conversation loads first
        }, 0);
        return;
      }
    }

    // If we reach here, we need to create a new window
    // Set show:true in createCodeaiAssistantWindow to show window immediately
    aiAssistantWindow = createCodeAIAssistantWindow();

    // Set position immediately to ensure window appears in the right place
    const position = getWindowPosition();
    aiAssistantWindow.setPosition(position.x, position.y, false);

    // Set UI mode after a minimal delay to ensure window is visible first
    if (aiAssistantWindow.webContents.isLoadingMainFrame()) {
      aiAssistantWindow.webContents.once('did-finish-load', () => {
        // First load the conversation
        console.log('New window ready - loading latest conversation first');
        aiAssistantWindow.webContents.send('load-latest-conversation');

        // Add a small delay before setting UI mode
        setTimeout(() => {
          console.log('Setting UI mode to SMART_CHAT in new window');
          aiAssistantWindow.webContents.send(
            'set-ui-mode',
            AIAssistantUIMode.SMART_CHAT,
            { keepExistingMessages: true }, // Flag to keep existing messages
          );
        }, 100);
      });
    } else {
      // First load the conversation
      console.log(
        'New window already loaded - loading latest conversation first',
      );
      aiAssistantWindow.webContents.send('load-latest-conversation');

      // Add a small delay before setting UI mode
      setTimeout(() => {
        console.log('Setting UI mode to SMART_CHAT in new window');
        aiAssistantWindow.webContents.send(
          'set-ui-mode',
          AIAssistantUIMode.SMART_CHAT,
          { keepExistingMessages: true }, // Flag to keep existing messages
        );
      }, 100);
    }

    // Focus window to bring it to front
    aiAssistantWindow.focus();
  };

  // Shortcut callback: AI Insight (Ctrl+Cmd+E)
  const aiInsightCallback = () => {
    // Simplified approach: directly read clipboard content
    const clipboardContent = clipboard.readText().trim();

    // Check if clipboard has content
    if (clipboardContent.length > 0) {
      // Check if code changed from last time
      const codeChanged = clipboardContent !== lastAnalyzedCodeToGetInsight;

      // If window exists and is visible and code hasn't changed, hide it
      if (
        aiAssistantWindow &&
        !aiAssistantWindow.isDestroyed() &&
        aiAssistantWindow.isVisible() &&
        !codeChanged
      ) {
        aiAssistantWindow.hide();
        return;
      }

      // Store the current clipboard content for tracking changes
      lastAnalyzedCodeToGetInsight = clipboardContent;

      // Create window if needed, otherwise use existing one
      if (!aiAssistantWindow || aiAssistantWindow.isDestroyed()) {
        aiAssistantWindow = createCodeAIAssistantWindow();
      }

      const processCode = () => {
        // Show the window if not visible
        if (!aiAssistantWindow.isVisible()) {
          showAIAssistantWindow();
        }

        // First, try to load existing conversation with matching code content
        // We'll need to add a new IPC event to handle this in the renderer
        if (isDebug) {
          console.log(
            `Trying to find existing conversation for code: ${clipboardContent.substring(0, 50)}...`,
          );
        }

        // Send code to analyze
        aiAssistantWindow.webContents.send(
          'code-to-generate-insight',
          clipboardContent,
        );

        // Set UI mode based on clipboard content and last insight state
        // If we had an insight for this code previously and are reopening, try to restore it
        if (
          clipboardContent === lastAnalyzedCodeToGetInsight &&
          lastInsightCompleted &&
          lastUIMode === AIAssistantUIMode.INSIGHT_CHAT
        ) {
          // Small delay to ensure window is fully loaded
          setTimeout(() => {
            // Important: First try to find matching conversation BEFORE setting UI mode
            // This allows the conversation to be loaded before UI logic runs
            console.log('Trying to find existing conversation for code');

            // Add event listener for one-time response from renderer process
            const findConversationResponseHandler = (event, success) => {
              console.log(
                `Find conversation response: ${success ? 'found' : 'not found'}`,
              );

              // If conversation was not found, proceed with normal insight generation
              if (!success) {
                console.log(
                  'Setting UI mode to INSIGHT_CHAT with restore flag',
                );

                // Set UI mode after we know if conversation exists
                aiAssistantWindow.webContents.send(
                  'set-ui-mode',
                  AIAssistantUIMode.INSIGHT_CHAT,
                  {
                    code: clipboardContent,
                    restoreInsight: true,
                  },
                );

                // Still request insight in case we need to regenerate it
                // The renderer will handle showing the cached insight if available
                anthropicService.analyzeCodeToGetInsight(
                  clipboardContent,
                  aiAssistantWindow,
                  { isRestored: true }, // Flag that this is a restored conversation
                );
              }

              // Remove one-time handler
              ipcMain.removeListener(
                'find-conversation-result',
                findConversationResponseHandler,
              );
            };

            // Register one-time event handler
            ipcMain.once(
              'find-conversation-result',
              findConversationResponseHandler,
            );

            // Send the find request
            aiAssistantWindow.webContents.send(
              'find-conversation-by-code',
              clipboardContent,
            );
          }, 100);
        } else {
          // Otherwise, use INSIGHT_CHAT mode and request a new insight
          setTimeout(() => {
            aiAssistantWindow.webContents.send(
              'set-ui-mode',
              AIAssistantUIMode.INSIGHT_CHAT,
              { code: clipboardContent },
            );

            // First try to load any existing matching conversation
            aiAssistantWindow.webContents.send(
              'find-conversation-by-code',
              clipboardContent,
            );

            // Request explanation (this is a new conversation)
            anthropicService.analyzeCodeToGetInsight(
              clipboardContent,
              aiAssistantWindow,
              { isRestored: false }, // Flag that this is a new conversation (explicit)
            );

            // Reset explanation completed flag
            lastInsightCompleted = false;
          }, 100);
        }
      };

      // Handle window loading state
      if (aiAssistantWindow.webContents.isLoadingMainFrame()) {
        aiAssistantWindow.webContents.once('did-finish-load', processCode);
      } else {
        processCode();
      }
    } else {
      // No content in clipboard - open pure chat interface

      // If window exists and is visible in PURE_CHAT mode, hide it
      // Since we can't directly know if it's in PURE_CHAT mode, we'll just hide it if empty clipboard
      if (
        aiAssistantWindow &&
        !aiAssistantWindow.isDestroyed() &&
        aiAssistantWindow.isVisible()
      ) {
        aiAssistantWindow.hide();
        return;
      }

      // Create or show aiAssistant window
      if (!aiAssistantWindow || aiAssistantWindow.isDestroyed()) {
        aiAssistantWindow = createCodeAIAssistantWindow();
      }

      // Set UI mode to PURE_CHAT
      if (aiAssistantWindow.webContents.isLoadingMainFrame()) {
        aiAssistantWindow.webContents.once('did-finish-load', () => {
          aiAssistantWindow.webContents.send(
            'set-ui-mode',
            AIAssistantUIMode.SMART_CHAT,
          );
        });
      } else {
        aiAssistantWindow.webContents.send(
          'set-ui-mode',
          AIAssistantUIMode.SMART_CHAT,
        );
      }

      // Show the window
      showAIAssistantWindow();
    }

    // End of the new implementation
  };

  // Shortcut callback: Terminal (Ctrl+Cmd+T) — toggle behavior like Quick Switcher
  const terminalCallback = () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      switcherWindow = createSwitcherWindow();
    }
    const window = getSwitcherWindow();
    if (window && window.isVisible()) {
      // If already showing Terminal tab, hide; otherwise switch to Terminal
      window.webContents.send('check-terminal-and-hide');
    } else if (window) {
      window.webContents.send('switch-to-terminal');
      showSwitcherWindow();
    }
  };

  // Map shortcut keys to their callbacks
  const shortcutCallbacks: Record<string, () => void> = {
    quickSwitcher: quickSwitcherCallback,
    aiInsight: aiInsightCallback,
    aiChat: aiChatCallback,
    terminal: terminalCallback,
  };

  // Register all shortcuts from settings (or defaults)
  const registerAllShortcuts = async () => {
    globalShortcut.unregisterAll();
    for (const key of Object.keys(DEFAULT_SHORTCUTS)) {
      const accelerator = ((await settings.get(`shortcut-${key}`)) as string) || DEFAULT_SHORTCUTS[key];
      const callback = shortcutCallbacks[key];
      if (callback) {
        const registered = globalShortcut.register(accelerator, callback);
        if (!registered && isDebug) {
          console.log(`Failed to register shortcut ${accelerator} for ${key}`);
        }
      }
    }
  };

  const getCurrentShortcuts = async (): Promise<ShortcutSettings> => ({
    quickSwitcher: ((await settings.get('shortcut-quickSwitcher')) as string) || DEFAULT_SHORTCUTS.quickSwitcher,
    aiInsight: ((await settings.get('shortcut-aiInsight')) as string) || DEFAULT_SHORTCUTS.aiInsight,
    aiChat: ((await settings.get('shortcut-aiChat')) as string) || DEFAULT_SHORTCUTS.aiChat,
    terminal: ((await settings.get('shortcut-terminal')) as string) || DEFAULT_SHORTCUTS.terminal,
  });

  const syncTrayShortcuts = async () => {
    if (tray) tray.updateShortcuts(await getCurrentShortcuts());
  };

  await registerAllShortcuts();
  await syncTrayShortcuts();

  // IPC handler: get all shortcut accelerators
  ipcMain.handle('get-shortcuts', async () => {
    return await getCurrentShortcuts();
  });

  // IPC handler: temporarily unregister a shortcut (while editing)
  ipcMain.handle('pause-shortcut', async (_event, key: string) => {
    if (!DEFAULT_SHORTCUTS[key]) return;
    const acc = ((await settings.get(`shortcut-${key}`)) as string) || DEFAULT_SHORTCUTS[key];
    globalShortcut.unregister(acc);
  });

  // IPC handler: re-register a shortcut (if editing was cancelled)
  ipcMain.handle('resume-shortcut', async (_event, key: string) => {
    if (!DEFAULT_SHORTCUTS[key]) return;
    const acc = ((await settings.get(`shortcut-${key}`)) as string) || DEFAULT_SHORTCUTS[key];
    const callback = shortcutCallbacks[key];
    if (callback) globalShortcut.register(acc, callback);
  });

  // IPC handler: set a single shortcut
  ipcMain.handle('set-shortcut', async (_event, key: string, accelerator: string) => {
    if (!DEFAULT_SHORTCUTS[key]) {
      return { success: false, error: 'Invalid shortcut key' };
    }

    const callback = shortcutCallbacks[key];
    if (!callback) {
      return { success: false, error: 'Invalid shortcut key' };
    }

    // Unregister the old shortcut for this key
    const oldAccelerator = ((await settings.get(`shortcut-${key}`)) as string) || DEFAULT_SHORTCUTS[key];
    globalShortcut.unregister(oldAccelerator);

    // Try to register the new shortcut
    const registered = globalShortcut.register(accelerator, callback);
    if (registered) {
      await settings.set(`shortcut-${key}`, accelerator);
      await syncTrayShortcuts();
      return { success: true };
    } else {
      // Re-register the old shortcut since the new one failed
      globalShortcut.register(oldAccelerator, callback);
      return { success: false, error: 'Shortcut already in use by another application' };
    }
  });

  // IPC handler: reset all shortcuts to defaults
  ipcMain.handle('reset-shortcuts', async () => {
    for (const key of Object.keys(DEFAULT_SHORTCUTS)) {
      await settings.unset(`shortcut-${key}`);
    }
    await registerAllShortcuts();
    await syncTrayShortcuts();
    return DEFAULT_SHORTCUTS;
  });
})();

// use lsof -i:55688 to check server process
// ref:
// 1. https://stackoverflow.com/questions/36031465/electron-kill-child-process-exec
// 2. https://stackoverflow.com/questions/42141191/electron-and-node-on-windows-kill-a-spawned-process
// Workaround to close all processes / sub-processes after closing the app
// app.once('window-all-closed', app.quit); ? seems not important
// mainWindow.removeAllListeners('close'); ? seems not important
app.once('before-quit', () => {
  if (serverProcess) {
    serverProcess.kill();
  }
});

ipcMain.handle('get-app-version', () => {
  return app.getVersion();
});

// Auto-update IPC handlers
ipcMain.on('check-for-update', () => {
  if (!isMAS()) {
    try {
      autoUpdater.checkForUpdates();
    } catch (e) {
      if (isDebug) {
        console.error('Manual update check failed:', e);
      }
      switcherWindow?.webContents.send('update-status', {
        status: 'error',
        error: e instanceof Error ? e.message : 'Update check failed',
      });
    }
  }
});

ipcMain.on('install-update', () => {
  autoUpdater.quitAndInstall();
});

ipcMain.handle('get-update-status', () => {
  return lastUpdateStatus;
});

// Terminal (node-pty) IPC handlers
let ptyProcess: any = null;
let ptyBuffer: string[] = []; // Buffer output until renderer connects
let ptyRendererReady = false;

const spawnTerminal = async (options: { cwd?: string; cols?: number; rows?: number } = {}) => {
  if (ptyProcess) {
    ptyProcess.kill();
    ptyProcess = null;
  }
  ptyBuffer = [];
  try {
    const pty = require('node-pty');
    const shell = process.env.SHELL || '/bin/zsh';
    const homePath = require('os').homedir();
    let cwd = options.cwd || homePath;
    // Try to read working folder from NestJS server
    if (!options.cwd) {
      try {
        const resp = await fetch('http://localhost:55688/user');
        const json = await resp.json();
        if (json?.workingFolder) cwd = json.workingFolder;
      } catch {}
    }
    ptyProcess = pty.spawn(shell, [], {
      name: 'xterm-256color',
      cols: options.cols || 80,
      rows: options.rows || 24,
      cwd,
      env: { ...process.env, TERM: 'xterm-256color' },
    });
    ptyProcess.onData((data: string) => {
      if (ptyRendererReady) {
        switcherWindow?.webContents.send('terminal-data', data);
      } else {
        ptyBuffer.push(data);
      }
    });
    ptyProcess.onExit(() => {
      switcherWindow?.webContents.send('terminal-exit');
      ptyProcess = null;
    });
  } catch (e) {
    if (isDebug) {
      console.error('Failed to spawn terminal:', e);
    }
  }
};

ipcMain.on('terminal-spawn', (_event, options: { cwd?: string; cols?: number; rows?: number }) => {
  ptyRendererReady = true;
  spawnTerminal(options);
});

ipcMain.on('terminal-attach', (_event, cols: number, rows: number) => {
  // Renderer is ready — resize to actual dimensions, then flush buffered output
  ptyRendererReady = true;
  if (ptyProcess) {
    ptyProcess.resize(cols, rows);
    // Small delay to let resize take effect, then clear and redraw prompt
    setTimeout(() => {
      // Send buffered data (discard — it was rendered at wrong size)
      ptyBuffer = [];
      // Send Ctrl+L to clear and redraw at correct size
      ptyProcess?.write('\x0c');
    }, 50);
  }
});

ipcMain.on('terminal-input', (_event, data: string) => {
  ptyProcess?.write(data);
});

ipcMain.on('terminal-resize', (_event, cols: number, rows: number) => {
  ptyProcess?.resize(cols, rows);
});

ipcMain.handle('terminal-is-spawned', () => {
  return ptyProcess !== null;
});

ipcMain.on('terminal-kill', () => {
  if (ptyProcess) {
    ptyProcess.kill();
    ptyProcess = null;
  }
});

// Login item settings are now controlled by the user via Settings UI toggle
ipcMain.handle('get-login-item-settings', () => {
  return app.getLoginItemSettings();
});

ipcMain.on('set-login-item-settings', (_event, openAtLogin: boolean) => {
  app.setLoginItemSettings({ openAtLogin });
});

// Session status hooks
let statusWatcherCleanup: (() => void) | null = null;

const initSessionStatusHooks = async () => {
  try {
    const enabled = (await settings.get('session-status-hooks')) !== false; // default: true
    if (enabled) {
      installHooks();
      // Start watching for status changes
      if (!statusWatcherCleanup) {
        statusWatcherCleanup = watchStatusDir((statuses) => {
          const obj: Record<string, SessionStatus> = {};
          statuses.forEach((v, k) => { obj[k] = v; });
          switcherWindow?.webContents.send('session-statuses-updated', obj);
        });
      }
    }
  } catch (e) {
    if (isDebug) console.error('Failed to init session status hooks:', e);
  }
};

ipcMain.handle('get-session-status-hooks-enabled', async () => {
  return (await settings.get('session-status-hooks')) !== false;
});

ipcMain.on('set-session-status-hooks-enabled', async (_event, enabled: boolean) => {
  await settings.set('session-status-hooks', enabled);
  if (enabled) {
    installHooks();
    if (!statusWatcherCleanup) {
      statusWatcherCleanup = watchStatusDir((statuses) => {
        const obj: Record<string, SessionStatus> = {};
        statuses.forEach((v, k) => { obj[k] = v; });
        switcherWindow?.webContents.send('session-statuses-updated', obj);
      });
    }
  } else {
    removeHooks();
    if (statusWatcherCleanup) {
      statusWatcherCleanup();
      statusWatcherCleanup = null;
    }
    // Clear renderer dots immediately
    switcherWindow?.webContents.send('session-statuses-updated', {});
  }
});

ipcMain.handle('get-session-statuses', async () => {
  // Return empty when hooks disabled — all dots revert to purple
  const enabled = (await settings.get('session-status-hooks')) !== false;
  if (!enabled) return {};

  const fileStatuses = readAllStatuses();
  const obj: Record<string, SessionStatus> = {};
  fileStatuses.forEach((v, k) => { obj[k] = v; });

  // Scan active sessions that don't have status files yet + cleanup stale ones
  try {
    const activeMap = await detectActiveSessions();
    cleanupStaleStatuses(new Set(activeMap.keys()));
    const allSessions = readClaudeSessions(500); // hoisted out of loop
    const sessionsWithoutStatus = Array.from(activeMap.entries())
      .filter(([sessionId]) => !obj[sessionId])
      .map(([sessionId]) => {
        const session = allSessions.find((s: any) => s.sessionId === sessionId);
        return session ? { sessionId, project: session.project } : null;
      })
      .filter(Boolean) as { sessionId: string; project: string }[];

    if (sessionsWithoutStatus.length > 0) {
      const scanned = await scanInitialStatuses(sessionsWithoutStatus);
      scanned.forEach((v, k) => {
        obj[k] = v;
        // Persist scanned status to file so fs.watch treats all statuses uniformly
        writeStatusFile(k, v as string);
      });
    }
  } catch {}

  return obj;
});

ipcMain.handle('get-session-terminal-app', async () => {
  return (await settings.get('session-terminal-app')) || 'iterm2';
});

ipcMain.on('set-session-terminal-app', async (_event, app: string) => {
  await settings.set('session-terminal-app', app);
});

ipcMain.handle('get-session-terminal-mode', async () => {
  return (await settings.get('session-terminal-mode')) || 'tab';
});

ipcMain.on('set-session-terminal-mode', async (_event, mode: string) => {
  await settings.set('session-terminal-mode', mode);
});

ipcMain.handle('get-session-display-mode', async () => {
  return (await settings.get('session-display-mode')) || 'first';
});

ipcMain.on('set-session-display-mode', async (_event, mode: string) => {
  await settings.set('session-display-mode', mode);
});

ipcMain.handle('get-default-switcher-mode', async () => {
  return (await settings.get('default-switcher-mode')) || 'projects';
});

ipcMain.on('set-default-switcher-mode', async (_event, mode: string) => {
  await settings.set('default-switcher-mode', mode);
});

// Claude Code session handlers
ipcMain.handle('get-claude-sessions', (_event, limit?: number) => {
  return readClaudeSessions(limit);
});

ipcMain.handle('search-claude-sessions', (_event, query: string) => {
  return searchClaudeSessions(query);
});

ipcMain.handle('detect-active-sessions', async () => {
  const activeMap = await detectActiveSessions();
  return Object.fromEntries(activeMap);
});

ipcMain.handle('detect-terminal-apps', async (_event, pidMap: Record<string, number>) => {
  const results: Record<string, string> = {};
  await Promise.all(Object.entries(pidMap).map(async ([sessionId, pid]) => {
    results[sessionId] = await detectTerminalApp(pid);
  }));
  return results;
});

ipcMain.on('open-claude-session', async (_event, sessionId: string, projectPath: string, isActive: boolean, activePid?: number, customTitle?: string) => {
  const terminalApp = ((await settings.get('session-terminal-app')) || 'iterm2') as string;
  const terminalMode = ((await settings.get('session-terminal-mode')) || 'tab') as string;
  openSession(sessionId, projectPath, isActive, activePid, terminalApp, terminalMode, customTitle);
});

ipcMain.on('copy-claude-session-command', (_event, sessionId: string, projectPath: string) => {
  copyResumeCommand(sessionId, projectPath);
});

ipcMain.handle('load-session-enrichment', async (_event, sessions: any[]) => {
  const { titles, branches, prLinks } = await loadSessionEnrichment(sessions);
  return {
    titles: Object.fromEntries(titles),
    branches: Object.fromEntries(branches),
    prLinks: Object.fromEntries(prLinks),
  };
});

ipcMain.handle('load-last-assistant-responses', async (_event, sessions: any[]) => {
  const responseMap = await loadLastAssistantResponses(sessions);
  return Object.fromEntries(responseMap);
});

ipcMain.handle('load-project-branches', async (_event, paths: string[]) => {
  const { exec } = require('child_process');
  const execPromise = (cmd: string): Promise<string> =>
    new Promise((resolve) => {
      exec(cmd, { encoding: 'utf-8', timeout: 2000 }, (_e: any, out: string) => resolve(out || ''));
    });

  const results: Record<string, string> = {};
  await Promise.all(
    paths.map(async (p: string) => {
      try {
        const branch = (await execPromise(`git -C "${p}" branch --show-current 2>/dev/null`)).trim();
        if (branch && branch !== 'HEAD') {
          results[p] = branch;
        }
      } catch {}
    }),
  );
  return results;
});

ipcMain.handle('detect-active-ide-projects', async () => {
  const folderNames = await detectActiveIDEProjects();
  return Array.from(folderNames);
});

app.dock.hide();
